### ISSUE TITLE
Deprecate strawberry_fields_listener.py

### ISSUE THREAD

**Issue by lneuhaus** [XanaduAI/blackbird#11]
The current version of the listener app does not work on my system:

```
$ python apps/strawberry_fields_listener.py examples/example_gbs.xbb 
Traceback (most recent call last):
  File "apps/strawberry_fields_listener.py", line 103, in <module>
    run(sys.argv[1])
  File "apps/strawberry_fields_listener.py", line 98, in run
    simulation.run()
AttributeError: 'BlackbirdProgram' object has no attribute 'run'
```

The listener should be updated to the new commands in version 0.1.0

**Comment by josh146** [comment]
Hi @lneuhaus. The latest master of Strawberry Fields now includes the ability to save and load blackbird scripts (https://github.com/XanaduAI/strawberryfields/pull/68), so this file is deprecated and I will likely remove it from the Blackbird repo - but thanks for flagging.

To develop using the Blackbird library, there have been a few changes introduced with PR #7. Namely,

* New top-level functions, to match the Python standard JSON library:
  - `blackbird.load` to load from a file
  - `blackbird.loads` to load from a string
  - `blackbird.dump` to save to a file
  - `blackbird.dumps` to save to a string

* `parse_blackbird` has been renamed to `parse`, and is no longer the recommended way to parse blackbird scripts.

The main reasons for these changes is to minimize the effect of blackbird syntax/grammar changes on dependent code-bases. Previously, a small grammar change could result in significant changes to the listener methods, meaning that all sub-classed listeners would need to be updated. Now, using `blackbird.load`, a [`BlackbirdProgram`](https://quantum-blackbird.readthedocs.io/en/latest/blackbird_python/program.html) object is returned, with attributes such as `modes`, `target`, `operation` to extract information about the program.

**Comment by lneuhaus** [comment]
Thanks for the comments, the new top-level functions work quite nicely and indeed make the Strawberry Fields listener exaple obsolete from my point of view.

**Comment by josh146** [comment]
Fixed in #12.
